baseurl: /twitter-archives

plugins:
  - jekyll-optional-front-matter

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
