domain: x4d3.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://x4d3.github.io/twitter-archive  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /twitter-archive/

plugins:
  - jekyll-optional-front-matter

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
