baseurl: /twitter-archives

plugins:
  - jekyll-optional-front-matter
  - jekyll-commonmark-ghpages

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
